run nickjj/flask-static-digest/gpt-4o-1

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,23 +1,69 @@
 name: CI
 
-on:
-  push:
-    branches:
-      - main
-  pull_request:
+on: [push, pull_request]
 
 jobs:
-  test:
+  build:
     runs-on: ubuntu-latest
     strategy:
+      fail-fast: false
       matrix:
-        python-version: [3.9, 3.8, 3.8]
+        python-version: ["3.8"]
+
     steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-python@v4
+      - uses: actions/checkout@v2
+
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v2
         with:
           python-version: ${{ matrix.python-version }}
+
       - name: Install dependencies
-        run: pip install . -r requirements.txt
+        run: |
+          python -m pip install -U pip
+          python -m pip install -U wheel
+          python -m pip install flake8 Flask==1.1.1
+          python -m pip install -e .
+
+      - name: Lint
+        run: |
+          flake8 .
+
       - name: Run tests
-        run: pytest
+        run: |
+          cd tests/example_app
+          export FLASK_APP=example.app
+
+          ls -laR example/static/ | wc -l | grep -q "26" \
+          && echo "File count before compiling test: pass" \
+          || (echo "File count before compiling test: fail" && exit 1)
+
+          flask digest compile \
+          && ls -laR example/static/ | wc -l | grep -q "36" \
+          && echo "File count after compiling test: pass" \
+          || (echo "File count after compiling test: fail" && exit 1)
+
+          grep -q "js/modules/hello.js" example/static/cache_manifest.json \
+          && echo "Cache manifest has nested file test: pass" \
+          || (echo "Cache manifest has nested file test: fail" && exit 1)
+
+          grep -q "js/modules/hello-d41d8cd98f00b204e9800998ecf8427e.js" example/static/cache_manifest.json \
+          && echo "Cache manifest has digested file test: pass" \
+          || (echo "Cache manifest has digested file test: fail" && exit 1)
+
+          flask run & \
+          sleep 5 \
+          && curl http://localhost:5000 | grep -q 'https://cdn.example.com/static/css/app-d41d8cd98f00b204e9800998ecf8427e.css' \
+          && echo 'Stylesheet is md5 tagged test: pass' \
+          || (echo 'Stylesheet is md5 tagged test: fail' && exit 1)
+
+          flask digest clean \
+          && ls -laR example/static/ | wc -l | grep -q "26" \
+          && echo "File count after cleaning test: pass" \
+          || (echo "File count after cleaning test: fail" && exit 1)
+
+          flask run -p 5001 & \
+          sleep 5 \
+          && curl http://localhost:5001 | grep -q 'https://cdn.example.com/static/js/app.js' \
+          && echo 'Javascript is not md5 tagged test: pass' \
+          || (echo 'Javascript is not md5 tagged test: fail' && exit 1)
